name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # <-- Ini nambahin tombol "Run workflow" di tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug
      run: ./gradlew assembleDebug

    - name: Build Release
      run: ./gradlew assembleRelease

    - name: Upload a Debug Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nexalloy-debug-apk
        path: app/build/outputs/apk/debug

    - name: Upload a Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nexalloy-release-apk
        path: |
          app/build/outputs/apk/release
          app/build/outputs/mapping/release/mapping.txt

    - name: Create AutoBuild Release
      run: |
        LATEST_REL=$(gh release view --json tagName -q .tagName 2>/dev/null || echo "")
        GIT_DESCRIBE=$(git rev-parse --short HEAD)
        cd app/build/outputs/apk/release/
        mv app-release.apk NexAlloy-${GIT_DESCRIBE}.apk
        gh release delete autobuild --yes 2>/dev/null || true
        gh release create autobuild NexAlloy-${GIT_DESCRIBE}.apk \
          --prerelease \
          --title "Nightly Build ${GIT_DESCRIBE}" \
          --notes "Nightly build from commit ${GIT_DESCRIBE}. See changes: https://github.com/${{ github.repository }}/compare/${LATEST_REL}...main"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
